FILE_UPLOAD <- "Select Data File"
SELECT_EXAMPLE <- "Choose Example File"
LAYERS <- "Show/Hide Layers"
BIN_NUMBER <- "Number of Shades"
FILL_OPACITY <- "Heatmap Opacity"
BANDWIDTH <- "Gaussian Radius Multiplier"
GRID_POINTS <- "Contour Smoothness"
DOWNLOAD_PLOT <- "Download Plot"
DOWNLOAD_TABLE <- "Download Table"