source("../global_ui.R")
library(leaflet)
library(d3heatmap)

shinyUI(list(HEAD_TASKS("#geomapTab"), fluidPage(title = "Geomap",
	
	sidebarLayout(position = "right",
		sidebarPanel(id = "sidebarPanel", width = 1,
			
			FILE_UPLOAD_PANEL(),
			EXAMPLE_FILE_SELECT(),
		
			tipify(fluidRow(
				column(3, tags$label("Area to use")),
				column(9, 
		    	selectInput("area", label = NULL, 
		    		choices = c(
		    			"World: By Country" = 'data/World_Countries.rds',
		    			"Africa: By Country" = 'data/Africa.rds', 
		    			"Asia: By Country" = 'data/Asia.rds', 
		    			"Europe: By Country" = 'data/Europe.rds', 
		    			"North America: By Country" = 'data/North_America.rds', 
		    			"South America: By Country" = 'data/South_America.rds', 
		    			
# 		    			"Canada: Level 2" = 'data/CAN_2.rds',
# 		    			"Canada: Level 3" = 'data/CAN_3.rds',
# 		    			"USA: Level 2" = 'data/USA_2.rds',
# 		    			"United Kingdom: Level 2" = 'data/GBR_2.rds',
# 		    			"Australia: Level 2" = 'data/AUS_2.rds',
		    			
"Afghanistan" = 'data/AFG_1.rds',
"Akrotiri and Dhekelia" = 'data/XAD_1.rds',
"Åland" = 'data/ALA_1.rds',
"Albania" = 'data/ALB_1.rds',
"Algeria" = 'data/DZA_1.rds',
"American Samoa" = 'data/ASM_1.rds',
"Andorra" = 'data/AND_1.rds',
"Angola" = 'data/AGO_1.rds',
"Antigua and Barbuda" = 'data/ATG_1.rds',
"Argentina" = 'data/ARG_1.rds',
"Armenia" = 'data/ARM_1.rds',
"Australia" = 'data/AUS_1.rds',
"Austria" = 'data/AUT_1.rds',
"Azerbaijan" = 'data/AZE_1.rds',
"Bahamas" = 'data/BHS_1.rds',
"Bahrain" = 'data/BHR_1.rds',
"Bangladesh" = 'data/BGD_1.rds',
"Barbados" = 'data/BRB_1.rds',
"Belarus" = 'data/BLR_1.rds',
"Belgium" = 'data/BEL_1.rds',
"Belize" = 'data/BLZ_1.rds',
"Benin" = 'data/BEN_1.rds',
"Bermuda" = 'data/BMU_1.rds',
"Bhutan" = 'data/BTN_1.rds',
"Bolivia" = 'data/BOL_1.rds',
"Bonaire, Saint Eustatius and Saba" = 'data/BES_1.rds',
"Bosnia and Herzegovina" = 'data/BIH_1.rds',
"Botswana" = 'data/BWA_1.rds',
"Brazil" = 'data/BRA_1.rds',
"British Virgin Islands" = 'data/VGB_1.rds',
"Brunei" = 'data/BRN_1.rds',
"Bulgaria" = 'data/BGR_1.rds',
"Burkina Faso" = 'data/BFA_1.rds',
"Burundi" = 'data/BDI_1.rds',
"Cambodia" = 'data/KHM_1.rds',
"Cameroon" = 'data/CMR_1.rds',
"Canada" = 'data/CAN_1.rds',
"Cape Verde" = 'data/CPV_1.rds',
"Cayman Islands" = 'data/CYM_1.rds',
"Central African Republic" = 'data/CAF_1.rds',
"Chad" = 'data/TCD_1.rds',
"Chile" = 'data/CHL_1.rds',
"China" = 'data/CHN_1.rds',
"Colombia" = 'data/COL_1.rds',
"Comoros" = 'data/COM_1.rds',
"Costa Rica" = 'data/CRI_1.rds',
"Côte d'Ivoire" = 'data/CIV_1.rds',
"Croatia" = 'data/HRV_1.rds',
"Cuba" = 'data/CUB_1.rds',
"Cyprus" = 'data/CYP_1.rds',
"Czech Republic" = 'data/CZE_1.rds',
"Democratic Republic of the Congo" = 'data/COD_1.rds',
"Denmark" = 'data/DNK_1.rds',
"Djibouti" = 'data/DJI_1.rds',
"Dominica" = 'data/DMA_1.rds',
"Dominican Republic" = 'data/DOM_1.rds',
"Ecuador" = 'data/ECU_1.rds',
"Egypt" = 'data/EGY_1.rds',
"El Salvador" = 'data/SLV_1.rds',
"Equatorial Guinea" = 'data/GNQ_1.rds',
"Eritrea" = 'data/ERI_1.rds',
"Estonia" = 'data/EST_1.rds',
"Ethiopia" = 'data/ETH_1.rds',
"Faroe Islands" = 'data/FRO_1.rds',
"Fiji" = 'data/FJI_1.rds',
"Finland" = 'data/FIN_1.rds',
"France" = 'data/FRA_1.rds',
"French Guiana" = 'data/GUF_1.rds',
"French Polynesia" = 'data/PYF_1.rds',
"French Southern Territories" = 'data/ATF_1.rds',
"Gabon" = 'data/GAB_1.rds',
"Gambia" = 'data/GMB_1.rds',
"Georgia" = 'data/GEO_1.rds',
"Germany" = 'data/DEU_1.rds',
"Ghana" = 'data/GHA_1.rds',
"Greece" = 'data/GRC_1.rds',
"Greenland" = 'data/GRL_1.rds',
"Grenada" = 'data/GRD_1.rds',
"Guadeloupe" = 'data/GLP_1.rds',
"Guam" = 'data/GUM_1.rds',
"Guatemala" = 'data/GTM_1.rds',
"Guinea-Bissau" = 'data/GNB_1.rds',
"Guinea" = 'data/GIN_1.rds',
"Guyana" = 'data/GUY_1.rds',
"Haiti" = 'data/HTI_1.rds',
"Honduras" = 'data/HND_1.rds',
"Hong Kong" = 'data/HKG_1.rds',
"Hungary" = 'data/HUN_1.rds',
"Iceland" = 'data/ISL_1.rds',
"India" = 'data/IND_1.rds',
"Indonesia" = 'data/IDN_1.rds',
"Iran" = 'data/IRN_1.rds',
"Iraq" = 'data/IRQ_1.rds',
"Ireland" = 'data/IRL_1.rds',
"Israel" = 'data/ISR_1.rds',
"Italy" = 'data/ITA_1.rds',
"Jamaica" = 'data/JAM_1.rds',
"Japan" = 'data/JPN_1.rds',
"Jordan" = 'data/JOR_1.rds',
"Kazakhstan" = 'data/KAZ_1.rds',
"Kenya" = 'data/KEN_1.rds',
"Kosovo" = 'data/XKO_1.rds',
"Kuwait" = 'data/KWT_1.rds',
"Kyrgyzstan" = 'data/KGZ_1.rds',
"Laos" = 'data/LAO_1.rds',
"Latvia" = 'data/LVA_1.rds',
"Lebanon" = 'data/LBN_1.rds',
"Lesotho" = 'data/LSO_1.rds',
"Liberia" = 'data/LBR_1.rds',
"Libya" = 'data/LBY_1.rds',
"Liechtenstein" = 'data/LIE_1.rds',
"Lithuania" = 'data/LTU_1.rds',
"Luxembourg" = 'data/LUX_1.rds',
"Macao" = 'data/MAC_1.rds',
"Macedonia" = 'data/MKD_1.rds',
"Madagascar" = 'data/MDG_1.rds',
"Malawi" = 'data/MWI_1.rds',
"Malaysia" = 'data/MYS_1.rds',
"Mali" = 'data/MLI_1.rds',
"Martinique" = 'data/MTQ_1.rds',
"Mauritania" = 'data/MRT_1.rds',
"Mauritius" = 'data/MUS_1.rds',
"Mayotte" = 'data/MYT_1.rds',
"Mexico" = 'data/MEX_1.rds',
"Micronesia" = 'data/FSM_1.rds',
"Moldova" = 'data/MDA_1.rds',
"Mongolia" = 'data/MNG_1.rds',
"Montenegro" = 'data/MNE_1.rds',
"Montserrat" = 'data/MSR_1.rds',
"Morocco" = 'data/MAR_1.rds',
"Mozambique" = 'data/MOZ_1.rds',
"Myanmar" = 'data/MMR_1.rds',
"Namibia" = 'data/NAM_1.rds',
"Nauru" = 'data/NRU_1.rds',
"Nepal" = 'data/NPL_1.rds',
"Netherlands" = 'data/NLD_1.rds',
"New Caledonia" = 'data/NCL_1.rds',
"New Zealand" = 'data/NZL_1.rds',
"Nicaragua" = 'data/NIC_1.rds',
"Niger" = 'data/NER_1.rds',
"Nigeria" = 'data/NGA_1.rds',
"North Korea" = 'data/PRK_1.rds',
"Northern Cyprus" = 'data/XNC_1.rds',
"Northern Mariana Islands" = 'data/MNP_1.rds',
"Norway" = 'data/NOR_1.rds',
"Oman" = 'data/OMN_1.rds',
"Pakistan" = 'data/PAK_1.rds',
"Palau" = 'data/PLW_1.rds',
"Palestina" = 'data/PSE_1.rds',
"Panama" = 'data/PAN_1.rds',
"Papua New Guinea" = 'data/PNG_1.rds',
"Paraguay" = 'data/PRY_1.rds',
"Peru" = 'data/PER_1.rds',
"Philippines" = 'data/PHL_1.rds',
"Poland" = 'data/POL_1.rds',
"Portugal" = 'data/PRT_1.rds',
"Puerto Rico" = 'data/PRI_1.rds',
"Qatar" = 'data/QAT_1.rds',
"Republic of Congo" = 'data/COG_1.rds',
"Reunion" = 'data/REU_1.rds',
"Romania" = 'data/ROU_1.rds',
"Russia" = 'data/RUS_1.rds',
"Rwanda" = 'data/RWA_1.rds',
"Saint Helena" = 'data/SHN_1.rds',
"Saint Kitts and Nevis" = 'data/KNA_1.rds',
"Saint Lucia" = 'data/LCA_1.rds',
"Saint Pierre and Miquelon" = 'data/SPM_1.rds',
"Saint Vincent and the Grenadines" = 'data/VCT_1.rds',
"Samoa" = 'data/WSM_1.rds',
"San Marino" = 'data/SMR_1.rds',
"Sao Tome and Principe" = 'data/STP_1.rds',
"Saudi Arabia" = 'data/SAU_1.rds',
"Senegal" = 'data/SEN_1.rds',
"Serbia" = 'data/SRB_1.rds',
"Sierra Leone" = 'data/SLE_1.rds',
"Slovakia" = 'data/SVK_1.rds',
"Slovenia" = 'data/SVN_1.rds',
"Solomon Islands" = 'data/SLB_1.rds',
"Somalia" = 'data/SOM_1.rds',
"South Africa" = 'data/ZAF_1.rds',
"South Korea" = 'data/KOR_1.rds',
"South Sudan" = 'data/SSD_1.rds',
"Spain" = 'data/ESP_1.rds',
"Sri Lanka" = 'data/LKA_1.rds',
"Sudan" = 'data/SDN_1.rds',
"Suriname" = 'data/SUR_1.rds',
"Svalbard and Jan Mayen" = 'data/SJM_1.rds',
"Swaziland" = 'data/SWZ_1.rds',
"Sweden" = 'data/SWE_1.rds',
"Switzerland" = 'data/CHE_1.rds',
"Syria" = 'data/SYR_1.rds',
"Taiwan" = 'data/TWN_1.rds',
"Tajikistan" = 'data/TJK_1.rds',
"Tanzania" = 'data/TZA_1.rds',
"Thailand" = 'data/THA_1.rds',
"Timor-Leste" = 'data/TLS_1.rds',
"Togo" = 'data/TGO_1.rds',
"Tokelau" = 'data/TKL_1.rds',
"Tonga" = 'data/TON_1.rds',
"Trinidad and Tobago" = 'data/TTO_1.rds',
"Tunisia" = 'data/TUN_1.rds',
"Turkey" = 'data/TUR_1.rds',
"Turkmenistan" = 'data/TKM_1.rds',
"Turks and Caicos Islands" = 'data/TCA_1.rds',
"Tuvalu" = 'data/TUV_1.rds',
"Uganda" = 'data/UGA_1.rds',
"Ukraine" = 'data/UKR_1.rds',
"United Arab Emirates" = 'data/ARE_1.rds',
"United Kingdom" = 'data/GBR_1.rds',
"United States Minor Outlying Islands" = 'data/UMI_1.rds',
"United States" = 'data/USA_1.rds',
"Uruguay" = 'data/URY_1.rds',
"Uzbekistan" = 'data/UZB_1.rds',
"Vanuatu" = 'data/VUT_1.rds',
"Venezuela" = 'data/VEN_1.rds',
"Vietnam" = 'data/VNM_1.rds',
"Virgin Islands, U.S." = 'data/VIR_1.rds',
"Wallis and Futuna" = 'data/WLF_1.rds',
"Western Sahara" = 'data/ESH_1.rds',
"Yemen" = 'data/YEM_1.rds',
"Zambia" = 'data/ZMB_1.rds',
"Zimbabwe" = 'data/ZWE_1.rds'

		    			),
		    		selected = 'data/World_Countries.rds'))
			), "Select map to display", placement = "right"),
			
			HTML("<button id='rangeSubmit' class='action-button clearButton'>Submit Range</button>"), 
			bsTooltip(id = "rangeSubmit", "Update heatmap using range of interest", placement = "right"),
			tags$label("Range of Interest"),
			tipify(
				sliderInput("range", 	   			
					label = NULL, 
			   	min = 0, 
			   	max = 100, 
			 		value = c(0, 100)), 
			"Adjust the colour assignment cutoff values, then click Submit Range button to update the heatmap", 
			placement = "right"),
			
			tipify(
				selectInput("colSelect", label = "Column to Use", choices = c(" " = 0)), 
				"Select column from input file", placement = "right"
				),
			
			LAYERS_SELECT(
				c("Map" = 'showTiles', "Contour Lines" = 'showContours', "Heatmap" = 'showHeatmap'), 
				c('showTiles', 'showContours', 'showHeatmap')
			),
			
			FILL_OPACITY_SLIDER(0.8),
			
			BIN_SLIDER(2, 12, 8),
			
      COLOUR_SCHEME_SELECT_LIMITED(),

      conditionalPanel(condition = "input.colourScheme == 'custom'", 
        JSCOLOUR_ROW("#FFEDA0", "#800026")
      ), 
		#	JSCOLOUR_ROW("#FFEDA0", "#800026"),

    	DOWNLOAD_BUTTONS(),
		 		
			ADVANCED_OPTIONS_PANEL(
				list(
					
					checkboxInput('detectRetina', label = "Scale map tiles on retina displays", value = FALSE),
						# On mixed display setups, user must load the page while the browser window is
						# positioned on a retina display, in addition to checking this box, in order
						# for retina-resolution map tiles to display.
					
					textInput('legend',
		    		label = "Custom legend title", 
		   			value = "Legend"), 
			
					sliderInput("lineSize", 
						label = "Contour Line Width", 
						min = 0,
						max = 5,
						value = 1)
				)
			)
	),
	mainPanel(id = "mainPanel",
		tabsetPanel(id = "tabSelections", type = "tabs",
			tabPanel(title = "Interactive", 
				tags$br(),
			  leafletOutput("map", "100%", 600),
				conditionalPanel("output.map",
					absolutePanel(id = "controls", class = "info legend leaflet-control", right = 30, top = 70, width=200,
			  		h4(strong("Region Information")),
			  		uiOutput("stateInfo")
					)
				)
			),
			tabPanel(title = "Table", 
				tags$br(),
				wellPanel(
					tags$label("Update Region Name"), 
					HTML("<button id='submitName' class='action-button clearButton'>Submit Name</button>"), 
					selectInput('tableNames', label = NULL, choices = c(" " = 0))		
				),
				DT::dataTableOutput("table")), 
			tabPanel(title = "Region Names", 
				tags$br(),
				DT::dataTableOutput("regionNames"))
			))),
	INCLUDE_JS()
)))
